name: release-only

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of the completed build-and-release run to pull artifacts from"
        required: true
      tag:
        description: "Existing tag to (re)publish (e.g., v0.0.0)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from previous run
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          path: ./artifacts
          merge-multiple: true

      - name: Publish GitHub Release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            artifacts/**/ffmpeg-whip-linux-*.tar.gz
            artifacts/**/ffmpeg-whip-linux-*.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
